# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
platform :ios

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Analytics'
end
